### PR TITLE
fix(client): hide register button on certain pages

### LINKED ISSUE #217: Remove "Register" Button from Activate Account
...it's causing confusion.

Image

### PR DESCRIPTION
**Pull request by nabryant299**
## Description

Don't show register button on `/register` and `/invitation_token/:token` pages

## Screenshots

N/A

## Related Issue

Closes #217 

## Pull Request Type

Please check the type of change your PR introduces:

- [x] Bugfix
- [ ] Feature
- [x] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation changes

## Checklist

- [x] My code follows the code style of this project.
- [ ] I have updated the documentation.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: src/layouts/Home.vue [hunk 1]
```diff
@@ -119,10 +123,16 @@ export default defineComponent({
       contact: t('publicNav.contact'),
     });
 
+    const route = useRoute();
+
+    //Hide register button on pages where the user is already registering or accepting an invitation
+    const hideRegister = route.name === "nav.register" || route.name === "nav.invitation_token";
```
Comment (tabiodun) [inline src/layouts/Home.vue:129]: I think this needs to be a computed property

**Review by deepanchal — APPROVED** [review]
@nabryant299 
Here is how you would fix this issue using slots. The changes you made would have worked fine. I made a refactor commit to provide you with an example of using vue slots :)

Here are my changes: https://github.com/CrisisCleanup/crisiscleanup-4-web/pull/229/commits/098945af7ff65327d6104d2e9604fc3ef8916a72
